title: Godly Gamers
description: >-
  Godly Gamers is a bot and website development company that can make you a
  website and discord bot or a game server and a vps panel
social_link: twitter
social_username: broccolini
github_repo: athena
github_username: broccolini
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /sartorial_dolls
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
